FROM kong:3.6

ENV KONG_DATABASE=off
ENV KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml

# reducir consumo
ENV KONG_NGINX_WORKER_PROCESSES=1
ENV KONG_MEM_CACHE_SIZE=32m
ENV KONG_PROXY_ACCESS_LOG=off
ENV KONG_ADMIN_ACCESS_LOG=off

COPY kong.yml /kong/declarative/kong.yml
